Added rule to prevent too early booking
cthit/bookIT-node pull request #31
Opened 2022-04-28 06:58 UTC by x183

Added a temporary workaround for issue #26.

2022-04-28 08:27 UTC, molleer commented
It works, but please use the `is_admin` variable instead of looking at `event.booked_as` to determine weather or not the user is admin. You can see how to use it here: https://github.com/cthit/bookIT-node/blob/0bba4c7a5c51abfbbd5ea2404ccd511ddb0e084f/backend/src/services/event.service.ts#L228

Also, you should be able of creating a new branch in the cthit/bookIT-node repo instead of a your forked repo since you are now digIT

2022-04-28 10:55 UTC, x183 commented
> It works, but please use the `is_admin` variable instead of looking at `event.booked_as` to determine weather or not the user is admin. You can see how to use it here:
> 
> https://github.com/cthit/bookIT-node/blob/0bba4c7a5c51abfbbd5ea2404ccd511ddb0e084f/backend/src/services/event.service.ts#L228
> 
> Also, you should be able of creating a new branch in the cthit/bookIT-node repo instead of a your forked repo since you are now digIT

Is fixed 😜

2022-04-28 21:23 UTC, molleer requested changes

2022-04-28 21:23 UTC, molleer commented on backend/src/services/event.service.ts
> +  if ((new Date(event.start) > new Date(Date.now() + 5443200000)) && is_admin) {
Shouldn't it be `&& !is_admin`?
Now the 9 week rule only applies to admins..

2022-05-02 15:36 UTC, molleer approved these changes
Look nice!

2022-05-02 15:37 UTC, merged