Added checks to validate phone numbers an email
cthit/bookIT-node pull request #37
Opened 2022-05-12 23:17 UTC by x183

Added checks to validate the phone numbers and email addresses of the event responsible.

2022-05-17 13:26 UTC, molleer requested changes

2022-05-19 14:57 UTC, molleer requested changes
When I edit the party report, the checks of phone number and email is not run.
This is due to the `editEvent` function does not use `editPartyReport`.

2022-05-20 11:19 UTC, x183 commented
Oops, missed to check that, should be sorted out now! 😉

2022-05-30 14:34 UTC, molleer approved these changes
Nice!

2022-05-30 14:34 UTC, merged