Add Co-responsible
cthit/bookIT-node pull request #49
Opened 2022-09-30 18:46 UTC by x183

Added fields for a co-responsible in EditEvent

2022-10-03 13:55 UTC, x183 commented
not fixed =(

2022-10-04 14:31 UTC, molleer requested changes
Looks nice, but the backend does not set co-responsible fields

2022-10-04 14:31 UTC, molleer commented on backend/src/services/party_report.service.ts
> +  console.log(party_report);
Remove this

2022-10-04 14:31 UTC, molleer commented on frontend/src/utils/utils.js
> +	console.log(date);
Remove this

2022-10-04 17:53 UTC, merged